[project]
name = "markitdown-api"
version = "0.1.0"
description = "An API wrapper to Microsoft's Markitdown library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "markitdown[all]>=0.1.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
]
